name: conventional-commits

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  pr-title:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: read
      pull-requests: write
      statuses: write
    steps:
      - uses: sethrylan/actions/conventional-commits@42d1fcce8d4108b5e06f4a0dacd6257edcf82832
